# Generated by Django 3.2 on 2023-06-17 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='activity_images')),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('carbon_footprint_reduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('land_saved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activity_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activitycategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activity_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activitycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.activitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activity_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hashtags', to='api.activitypost')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.activitypost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activitypost',
            name='sub_activity_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subactivitycategory'),
        ),
        migrations.AddField(
            model_name='activitypost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
