# Generated by Django 3.2 on 2023-06-17 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230617_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubActivityCategoryChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='subactivitycategory',
            name='activity_choices',
        ),
        migrations.DeleteModel(
            name='SubActivityChoices',
        ),
        migrations.AddField(
            model_name='subactivitycategorychoices',
            name='sub_activity_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subactivitycategory'),
        ),
    ]
