# Generated by Django 3.2 on 2023-06-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230617_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subactivitycategory',
            name='task_method',
            field=models.CharField(blank=True, choices=[('Had', 'Had'), ('Prepared', 'Prepared')], max_length=20, null=True),
        ),
    ]
