# Generated by Django 3.2 on 2023-06-17 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230617_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitypost',
            name='sub_activity_category_choices',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.subactivitycategorychoices'),
            preserve_default=False,
        ),
    ]
