# Generated by Django 3.2 on 2023-06-17 04:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_alter_userfollowers_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowers',
            name='followers',
            field=models.ManyToManyField(related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserFollowings',
        ),
    ]
