# Generated by Django 3.2 on 2023-06-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_imageclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageclassification',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
