# Generated by Django 3.2 on 2023-06-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_imageclassification_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageclassification',
            name='predicted_labels',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
